### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by ronbere** [namkazt/sd-webui-prompt-history#1]
AttributeError: module 'modules.images' has no attribute 'save_image_with_geninfo'
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.50it/s]
12:32:34-610368 ERROR    Exception: module 'modules.images' has no attribute 'save_image_with_geninfo'
12:32:34-611370 ERROR    Arguments: args=('task(7dn3cjeb090c7dn)', 'Handsome Disney prince, Pixar style', '',
                         ['Default_Negative'], 20, 0, False, False, 1, 1, 6, 1, -1.0, -1.0, 0, 0, 0, False, 512, 512,
                         False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96,
                         96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2,
                         0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2,
                         -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2,
                         '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         2048, 128, True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002DC5B30D030>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002DC5B1B0FA0>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002DC5B2375B0>,
                         False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '',
                         'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0,
                         'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False,
                         'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28,
                         'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model':
                         'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0,
                         'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt':
                         '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0,
                         'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False,
                         'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28,
                         'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model':
                         'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0,
                         'ad_controlnet_guidance_end': 1}, None, False, '0',
                         'C:\\automatic\\extensions/sd-webui-faceswap/models\\inswapper_128.onnx', 'CodeFormer', 1, '',
                         1, 1, False, True, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1,
                         1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', 7, '', [], 0,
                         '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False,
                         None, None, False, 50) kwargs={}
12:32:34-618376 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ C:\automatic\modules\call_queue.py:34 in f                                                                          │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ C:\automatic\modules\txt2img.py:56 in txt2img                                                                       │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ ❱ 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│ C:\automatic\extensions\sd-webui-prompt-history\lib_history\image_process_hijacker.py:29 in process_images          │
│                                                                                                                     │
│   28 │   img = res.images[0]                                                                                        │
│ ❱ 29 │   images.save_image_with_geninfo(img, None, os.path.join(global_state.history_path, f"                       │
│   30 │   # add result to history                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'modules.images' has no attribute 'save_image_with_geninfo'

Windows11, Firefox

**Comment by namkazt** [comment]
what version of webui you are using?

**Comment by ronbere** [comment]
this one:

Using VENV: C:\automatic\venv
12:38:56-192546 INFO     Starting SD.Next
12:38:56-195549 INFO     Python 3.10.9 on Windows
12:38:56-233088 INFO     Version: 9334b2f2 Wed Jun 14 13:54:23 2023 -0400
12:38:56-449294 INFO     Latest published version: 618097dac275aed3a09f0cc11ad74389dd99b649 2023-06-14T22:19:28Z
12:38:56-451296 INFO     nVidia CUDA toolkit detected
12:38:57-594897 INFO     Torch 2.0.1+cu118
12:38:57-604906 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:38:57-605907 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80

**Comment by namkazt** [comment]
yeah, your version is not supported,  please use official version or just pull from master or dev branch

-> https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/9334b2f21c72dada20de6d9d9aacaba83940906b/modules/images.py

your version do not have that function `save_image_with_geninfo`
