### ISSUE TITLE
Something in data folder preventing Automatic1111 from reloading UI

### ISSUE THREAD

**Issue by eliluong** [namkazt/sd-webui-prompt-history#10]
Hello, for the past week I have been having an issue where reloading UI in Automatic1111 will be stuck, so I would have to restart the entire application for it to work again. I use https://github.com/AbdBarho/stable-diffusion-webui-docker to run, so I am not sure if there are any additional error messages that might show, but I do not see any in my console. Today when making a fresh copy of Automatic1111, I copied the old `data` folder from this extension to the new copy. After this, the same issue (stuck on reloading UI) occurred, so I deleted `data` folder and it is fine now.

Please let me know if you would like to investigate if there is no other cause you can think of that I can try, I can email my `data.json` file to you. Thanks!

**Comment by namkazt** [comment]
Reload UI is another problem that is not related to `data` folder. it is maybe caused by gradio unable to release coroutine jobs.

**Comment by eliluong** [comment]
Hmm, I think you are right. I use the "Apply and restart UI" in Extensions > Installed tab and it works, after I moved old data back in. But anywhere it says "Reload UI" it will get stuck even without sd-webui-prompt-history extension. I will close. Thank you for your time.
