### ISSUE TITLE
[Windows] - Prompt History tab keeps loading

### ISSUE THREAD

**Issue by KevinDenys** [namkazt/sd-webui-prompt-history#11]
![image](https://github.com/namkazt/sd-webui-prompt-history/assets/17174443/98b77aa2-2357-4a59-8ffd-be7a57250396)

The data folder contains data.json and images so they are being saved. But the History tab keeps loading, no errors or anything

**Comment by jchollon** [comment]
Same for me...

**Comment by namkazt** [comment]
> ![image](https://user-images.githubusercontent.com/17174443/250123753-98b77aa2-2357-4a59-8ffd-be7a57250396.png)
> 
> The data folder contains data.json and images so they are being saved. But the History tab keeps loading, no errors or anything

can you provide steps to reproduce this? maybe zip data folder and send me if it is ok

**Comment by jchollon** [comment]
This seems to be fixed.   I'm not having the issue anymore.

**Comment by namkazt** [comment]
close as unable to reproduce.
