### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jchollon** [namkazt/sd-webui-prompt-history#12]
It would be nice to be able to select multiple history items and batch delete.

**Comment by namkazt** [comment]
> It would be nice to be able to select multiple history items and batch delete.

@jchollon  there is a PR for that, I'm review and working on that https://github.com/namkazt/sd-webui-prompt-history/pull/14

**Comment by namkazt** [comment]
implemented on https://github.com/namkazt/sd-webui-prompt-history/commit/bde3e95e078b107efe78f0608a62b163daceb6d3
