### ISSUE TITLE
I enhanced some features like batch delete, prompt image etc. You can merge it together so that everyone can use this plugin better.

### ISSUE THREAD

**Issue by 12343954** [namkazt/sd-webui-prompt-history#13]
https://github.com/12343954/sd-webui-prompt-history

<img width="785" alt="image" src="https://github.com/namkazt/sd-webui-prompt-history/assets/1804003/adfbbbda-488b-4a08-b046-6a99100b896b">

**Comment by namkazt** [comment]
sound cool, please create a PR

**Comment by 12343954** [comment]
ok, PR has been created.

**Comment by namkazt** [comment]
thanks, all ideas are implemented:
https://github.com/namkazt/sd-webui-prompt-history/commit/bde3e95e078b107efe78f0608a62b163daceb6d3
7d7050bc95ba8719bc81c70dbb248ece56729596
