### ISSUE TITLE
Show small thumbnails in the list

### ISSUE THREAD

**Issue by Centurion-Rome** [namkazt/sd-webui-prompt-history#17]
It would be nice if you could show small thumbnails on lists left side . It would be more intuitive to select item instead of clicking each one to find image that you have in memory ;)

Thank you!

**Comment by namkazt** [comment]
yes, it will be implemented soon

**Comment by namkazt** [comment]
implemented in commit: https://github.com/namkazt/sd-webui-prompt-history/commit/7d7050bc95ba8719bc81c70dbb248ece56729596
