### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by Comethri** [namkazt/sd-webui-prompt-history#2]
Could you fix dark mode?

![ss+(2023-06-15+at+01 59 39)](https://github.com/namkazt/sd-webui-prompt-history/assets/51615283/4a75f746-af0d-4719-9feb-8bea19a28a6a)

**Comment by namkazt** [comment]
fixed with latest commit: 
![image](https://github.com/namkazt/sd-webui-prompt-history/assets/6035916/89bef2ee-1c84-4cd2-a19a-b8cdc6d23503)
