### ISSUE TITLE
GradioDeprecationWarning: The `style` method is deprecated. 

### ISSUE THREAD

**Issue by illuculent** [namkazt/sd-webui-prompt-history#24]
WARNING:py.warnings:C:\stable-diffusion\Packages\stable-diffusion-webui\extensions\sd-webui-prompt-history\scripts\prompt_history_script.py:146: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  preview_image = gr.Image(
I get this warning every load.

**Comment by namkazt** [comment]
fixed in last commit. 3fb37abb778df779113e8977b4fe5c735e3b1d84
