### ISSUE TITLE
Is it possible to hide the "Save Last Generated Info" button in t2i?

### ISSUE THREAD

**Issue by player99963** [namkazt/sd-webui-prompt-history#26]
This button takes up too much space and I was hoping to find a setting to hide it, but there doesn't seem to be one.
Also I'm not sure what effect it has as it doesn't seem to do anything when I click it.
![image](https://github.com/namkazt/sd-webui-prompt-history/assets/36121614/c3585e3f-9cde-4bd0-bc3e-dd83ed877eb3)

**Comment by namkazt** [comment]
it was meant for manual save generation that you like other than autosave it. but currently extension is broken.

**Comment by namkazt** [comment]
closed as not fix, 

1, Enable automatic save will hide the button
2, click on it will save the prompt history ( it just do not have any effect, sorry about that )
