### ISSUE TITLE
Appears broken

### ISSUE THREAD

**Issue by TubeStorm** [namkazt/sd-webui-prompt-history#5]
Hey,
Not sure what's this page supposed to show. 
Could you also add more instructions incase I'm doing something wrong.

![image](https://github.com/namkazt/sd-webui-prompt-history/assets/18316153/ab83d923-17d2-4ac6-b51a-2a94a9a1a02a)

**Comment by seedlord** [comment]
it will list your last prompts and the corresponding image when you generate.

generate a few images and then look again into that tab.
you are using dark ui theme. sadly the ui of this extension is not adapted to darkui. you need to make some changes in style.css

**Comment by namkazt** [comment]
> Hey, Not sure what's this page supposed to show. Could you also add more instructions incase I'm doing something wrong.
> 
> ![image](https://user-images.githubusercontent.com/18316153/246231699-ab83d923-17d2-4ac6-b51a-2a94a9a1a02a.png)

Hi @TubeStorm,

This tool automatically stored almost all your prompt and setting of `txt2img`, it will appear in history tab when you generated anything.

Just select the history and click apply, also please update the extensions.

**Comment by TubeStorm** [comment]
Hello,
Thanks for clearing it up.
