### ISSUE TITLE
TypeError 'float' object cannot be interpreted as an integer - when enabling Automatic Save in settings

### ISSUE THREAD

**Issue by leontheremin** [namkazt/sd-webui-prompt-history#7]
Kind of new to the SD ecosystem. Been tinkering for a few days with it, getting more and more extensions, today especially, so this might be as well some conflict with other extensions. My latest experiments were to save the state of checkpoint and ControlNet settings. 

version [9a97eeff](https://github.com/namkazt/sd-webui-prompt-history/commit/9a97eeff81985dc9d4eaf0b4f39a09a083b2b3d0)
Fri Jun 16 09:39:37 2023

I'm getting this error when I try to generate with any settings. ControlNet is disabled

Error completing request███████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 11.05it/s]
Arguments: ('task(nb2r8smmhldxhxv)', 'sunset in the mountains', '', [], 21, 16, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002342CEB1660>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002342CEB0D90>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002342CEB3940>, None, False, '0', 'M:\\AI\\stable-diffusion-webui\\extensions/sd-webui-faceswap/models\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, 1, 0, '', '', 20, True, 20, True, 4, 0.4, 7, 512, 512, True, 88, False, 'None', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50, True, 0, '', '', 20, True, 20, True, 4, 0.4, 7, 512, 512, True, 88, False, 'None') {}
Traceback (most recent call last):
  File "M:\AI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "M:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "M:\AI\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "M:\AI\stable-diffusion-webui\extensions\sd-webui-prompt-history\lib_history\image_process_hijacker.py", line 25, in process_images
    global_state.add_config( uuid.uuid4().hex, res.prompt[:64], shared.opts.sd_model_checkpoint, res.infotexts[0], res.images[0])
  File "M:\AI\stable-diffusion-webui\extensions\sd-webui-prompt-history\scripts\prompt_history_script.py", line 69, in add_config
    img = img.resize((new_width, new_height), Image.LANCZOS)
  File "M:\AI\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2193, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: 'float' object cannot be interpreted as an integer

**Comment by FutonGama** [comment]
same here

**Comment by namkazt** [comment]
fixed in last commit: https://github.com/namkazt/sd-webui-prompt-history/commit/b3236529385f3dbdf20a637c7f62625b8c8b8feb
